environment_file: "$(find smarc_stonefish_worlds)/data/algae/algae_env_small.scn"
latitude: "58.250833"
longitude: "11.450283"
algae_texture_dir: "$(find smarc_stonefish_worlds)/data/algae/textures"
mesh: {
    anchoring_buoy_rope: "$(find smarc_stonefish_worlds)/data/algae/components/anchoring_chain.obj",
    a0_buoy: "$(find smarc_stonefish_worlds)/data/algae/components/a0_buoy.obj",
    rope: "$(find smarc_stonefish_worlds)/data/algae/components/a0_buoy_ropes_small_farm.obj",
    algae_row1: "$(find smarc_stonefish_worlds)/data/algae/components/algae_row1_small_farm.obj",
    algae_row2: "$(find smarc_stonefish_worlds)/data/algae/components/algae_row2_small_farm.obj"
}
marked_positions: {
    buoy_corner1: {position: "4.00 -5.00 0.00", orientation: "0.00 0.00 0.00", color: "white", mesh: "a0_buoy"},
    buoy_corner2: {position: "4.00 5.00 0.00", orientation: "0.00 0.00 0.00", color: "white", mesh: "a0_buoy"},
    buoy_corner3: {position: "14.00 -5.00 0.00", orientation: "0.00 0.00 0.00", color: "white", mesh: "a0_buoy"},
    buoy_corner4: {position: "14.00 5.00 0.00", orientation: "0.00 0.00 0.00", color: "white", mesh: "a0_buoy"},
    buoy_mid1: {position: "9.00 -5.00 0.00", orientation: "0.00 0.00 0.00", color: "red", mesh: "a0_buoy"},
    buoy_mid2: {position: "9.00 5.00 0.00", orientation: "0.00 0.00 0.00", color: "red", mesh: "a0_buoy"}
}
